### ISSUE TITLE
Pulling data from hass does not work

### ISSUE THREAD

**Issue by RalfPfitzner** [davidusb-geek/emhass-add-on#28]
Hi David,

I'm encountering this behaviour from EMHASS:

[2022-09-14 14:07:47,182] INFO in web_server: Launching the emhass webserver at: http://0.0.0.0:5000
[2022-09-14 14:07:47,182] INFO in web_server: Home Assistant data fetch will be performed using url: http://supervisor/core/api
[2022-09-14 14:07:47,182] INFO in web_server: The base path is: /usr/src
[2022-09-14 14:07:47,183] INFO in web_server: Using core emhass version: 0.3.18
[2022-09-14 14:08:08,988] INFO in web_server: EMHASS server online, serving index.html...
[2022-09-14 14:08:30,780] INFO in command_line: Setting up needed data
[2022-09-14 14:08:30,811] INFO in forecast: Retrieving weather forecast data using method = scrapper
[2022-09-14 14:08:34,036] INFO in forecast: Retrieving data from hass for load forecast using method = naive
[2022-09-14 14:08:34,036] INFO in retrieve_hass: Retrieve hass get data method initiated...
[2022-09-14 14:08:34,051] ERROR in retrieve_hass: The retrieved JSON is empty, check that correct day or variable names are passed
[2022-09-14 14:08:34,051] ERROR in retrieve_hass: Either the names of the passed variables are not correct or days_to_retrieve is larger than the recorded history of your sensor (check your recorder settings)
[2022-09-14 14:08:34,051] ERROR in app: Exception on /action/dayahead-optim [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/local/lib/python3.9/dist-packages/emhass/web_server.py", line 134, in action_call
    input_data_dict = set_input_data_dict(config_path, str(config_path.parent), costfun,
  File "/usr/local/lib/python3.9/dist-packages/emhass/command_line.py", line 77, in set_input_data_dict
    P_load_forecast = fcst.get_load_forecast(method=optim_conf['load_forecast_method'])
  File "/usr/local/lib/python3.9/dist-packages/emhass/forecast.py", line 495, in get_load_forecast
    rh.get_data(days_list, var_list)
  File "/usr/local/lib/python3.9/dist-packages/emhass/retrieve_hass.py", line 130, in get_data
    self.df_final = pd.concat([self.df_final, df_day], axis=0)
UnboundLocalError: local variable 'df_day' referenced before assignment

As my sensor for the load of the house without the deferrable load is only a calculated value and the update frequency of my energy sensor and the pv don't match I sometimes have negative values for the currently used power. Could this affect the EMHASS?

I'm also waiting for the implementation of the solcast values in the add-on to have the right values for my specific installation of the solar panels (installed on both sides of the house, 40% east, 60% west).

Just to mention, it looks like EMHASS is not at the right day (the graphs are showing dates as of April this year). Is this a config error?

Thanks for looking into that. If you need more data or config just send a message.

Thanks
Ralf

**Comment by davidusb-geek** [comment]
Hi, this error is well known and the error message was made explicit for this reason. So, check that the correct day or variable names are passed. Either the names of the passed variables are not correct or days_to_retrieve is larger than the recorded history of your sensor (check your recorder settings). Check the data entering EMHASS using templates in Home Assistant.

> As my sensor for the load of the house without the deferrable load is only a calculated value and the update frequency of my energy sensor and the pv don't match I sometimes have negative values for the currently used power. Could this affect the EMHASS?

This is not a problem, there is a parameters in the configuration to control this (`set_zero_min`). Take a look at the docs here: https://emhass.readthedocs.io/en/latest/config.html

> I'm also waiting for the implementation of the solcast values in the add-on to have the right values for my specific installation of the solar panels (installed on both sides of the house, 40% east, 60% west).

I'll implement this in the next version of the add-on when I could find some spare time to work on this. But for now you can already implement this by using rest sensors and passing the data using templates and list. Follow the example given in the docs here: https://emhass.readthedocs.io/en/latest/forecasts.html#example-using-solcast-forecast-amber-prices

> Just to mention, it looks like EMHASS is not at the right day (the graphs are showing dates as of April this year). Is this a config error?

This is normal as this is just the example results form the default configuration, so this is not refelcting your system. You need to run a proper otimization first to update this figure. So this means that you need to solve the first issue first and then you will be able to see the updated graphs.

**Comment by RalfPfitzner** [comment]
Dumb me, parameter for pv was not set at all (though I think I did it....), what ever.

Now that part is working, next problem comes up. I have left the params for the solver at the default values. So lp_solver is set to PULP_CBC_CMD and lp_solver_path is set to the string "empty" (did not change it). That's also what the documentation says (no that I understand that the string "empty" has to be there...).

[2022-09-14 14:55:57,306] INFO in optimization: Solving for day: 12-9-2022
[2022-09-14 14:55:57,326] ERROR in optimization: It was not possible to find a valid solver for Pulp package
[2022-09-14 14:55:57,326] INFO in optimization: Status: Not Solved
[2022-09-14 14:55:57,326] WARNING in optimization: Cost function cannot be evaluated, probably None
[2022-09-14 14:55:57,329] ERROR in app: Exception on /action/perfect-optim [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/local/lib/python3.9/dist-packages/emhass/web_server.py", line 143, in action_call
    opt_res = perfect_forecast_optim(input_data_dict, app.logger)
  File "/usr/local/lib/python3.9/dist-packages/emhass/command_line.py", line 161, in perfect_forecast_optim
    opt_res = input_data_dict['opt'].perform_perfect_forecast_optim(df_input_data, input_data_dict['days_list'])
  File "/usr/local/lib/python3.9/dist-packages/emhass/optimization.py", line 462, in perform_perfect_forecast_optim
    opt_tp = self.perform_optimization(data_tp, P_PV, P_load,
  File "/usr/local/lib/python3.9/dist-packages/emhass/optimization.py", line 386, in perform_optimization
    opt_tp["P_grid"] = [P_grid_pos[i].varValue + P_grid_neg[i].varValue for i in set_I]
  File "/usr/local/lib/python3.9/dist-packages/emhass/optimization.py", line 386, in <listcomp>
    opt_tp["P_grid"] = [P_grid_pos[i].varValue + P_grid_neg[i].varValue for i in set_I]
TypeError: unsupported operand type(s) for +: 'NoneType' and 'NoneType'

**Comment by davidusb-geek** [comment]
Yes, this is another. I'll try to test this at home as this seems to be a new problem that other users have also found. I'll come back later when I can with an answer to this after the tests.

**Comment by RalfPfitzner** [comment]
Question about the set_zero_min parameter:

According to the mentioned docs it set to true by default.

As I'm using the add-on this parameter is not available in the config page of the add-on. That's a little bit strange. Do I have to dig in some files in a container to find the config_emhass.yaml file to change it?

**Comment by RalfPfitzner** [comment]
> Yes, this is another. I'll try to test this at home as this seems to be a new problem that other users have also found. I'll come back later when I can with an answer to this after the tests.

GLPK_CMD is working!

**Comment by davidusb-geek** [comment]
Oh yes you're right, this is a parameter that is True by default and it can't be changed from the add-on. There are some parameters that can be updated from the add-on, the initial goal of this was to simplify the list of editable parameters and simplify usability of the add-on

**Comment by davidusb-geek** [comment]
> 

Ok great! Still a solution needs to be found because the other solvers are normally there on your system and we just need to provide the correct path to the executables. The default solvers are normally more robust and efficient than GLPK

**Comment by RalfPfitzner** [comment]
> > GLPK_CMD is working!
> 
> Ok great! Still a solution needs to be found because the other solvers are normally there on your system and we just need to provide the correct path to the executables. The default solvers are normally more robust and efficient than GLPK

Thanks for the support.
Day-ahead not working yet as I still have to implement the forecast data now :-) 
Will stay tuned to this project! Good job!

**Comment by davidusb-geek** [comment]
Hi, for the last problem I've just changed the default values for these:
```
  lp_solver: COIN_CMD
  lp_solver_path: /usr/bin/cbc
```
Everything is just working fine now.
Feel free to open another issue if necessary

**Comment by davidusb-geek** [comment]
> Day-ahead not working yet as I still have to implement the forecast data now :-)

Hi, concerning this, SolCast can now be used natively on emhass.
Follow these instructions: https://emhass.readthedocs.io/en/latest/forecasts.html#pv-power-production-forecast
