### ISSUE TITLE
Using emhass addon on a another pc and accessing Home Assistant sensors

### ISSUE THREAD

**Issue by overas** [davidusb-geek/emhass-add-on#38]
Home Assistant 2023.3.1
Supervisor 2023.01.1
Operating System 9.5
Frontend 20230302.0 - latest
EMHASS
Current version: 0.3.1

Today I have the emhass addon installed on a Home Assistant Yellow pc. As this is not powerful enough to do emhass optimization, I would like to be able to use an Intel nuc for this. 
I have set up hassos on my Intel nuc and installed emhass addon in this Home Assistant instance. In the emhass settings I use the ip for my home assistant yellow pc and token. I also changed to the pv_power sensor and load_power_without_deferral_loads which I use:

```
hass_url: http://x.x.x.x:8123
token: xxxxxxxxxxxx
pv_power_production: sensor.ecu_current_power
load_power_without_deferral_loads: sensor.power_load_no_var_loads
```

When I do a Day-ahead optimization from the Intel nuc webpage I get errors about "Variable sensor.power_load_no_var_loads was not found."  Is it possible to use emhass addon on another pc to access home assistant sensors?

Emhass log:
```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun emhass (no readiness notification)
s6-rc: info: service legacy-services successfully started
waitress   INFO  Serving on http://0.0.0.0:5000
The data container dictionary is empty... Please launch an optimization task
Variable sensor.power_load_no_var_loads was not found. This is typically because no data could be retrieved from Home Assistant
Exception on /action/dayahead-optim [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/local/lib/python3.9/dist-packages/emhass/web_server.py", line 150, in action_call
    input_data_dict = set_input_data_dict(config_path, str(data_path), costfun,
  File "/usr/local/lib/python3.9/dist-packages/emhass/command_line.py", line 91, in set_input_data_dict
    P_load_forecast = fcst.get_load_forecast(method=optim_conf['load_forecast_method'])
  File "/usr/local/lib/python3.9/dist-packages/emhass/forecast.py", line 586, in get_load_forecast
    rh.prepare_data(self.retrieve_hass_conf['var_load'], load_negative = self.retrieve_hass_conf['load_negative'],
  File "/usr/local/lib/python3.9/dist-packages/emhass/retrieve_hass.py", line 187, in prepare_data
    self.df_final.drop([var_load], inplace=True, axis=1)
  File "/usr/local/lib/python3.9/dist-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/pandas/core/frame.py", line 4948, in drop
    return super().drop(
  File "/usr/local/lib/python3.9/dist-packages/pandas/core/generic.py", line 4279, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
  File "/usr/local/lib/python3.9/dist-packages/pandas/core/generic.py", line 4323, in _drop_axis
    new_axis = axis.drop(labels, errors=errors)
  File "/usr/local/lib/python3.9/dist-packages/pandas/core/indexes/base.py", line 6644, in drop
    raise KeyError(f"{list(labels[mask])} not found in axis")
KeyError: "['sensor.power_load_no_var_loads'] not found in axis"
```

**Comment by davidusb-geek** [comment]
To make it work this way you need to make the `hass_url` accessible from outside your LAN. Do this securely of course, by using duckdns or other services and encryption. 
And the token should be of course a valid long live access token.

**Comment by overas** [comment]
Thanks you for fast answer. I going to try to use Home Assistant Cloud Remote Control url. I going to give you feedback how it goes.

**Comment by overas** [comment]
Tried with Home Assistant Cloud Remote Control url and valid long live access token. When emhass starts up I get a lot of errors in the log. If emhass supported Ingress I think it has been easier to connect (https://www.nabucasa.com/config/remote/).

![image](https://user-images.githubusercontent.com/37910044/223518924-88f5d765-51e9-4a5f-bc8f-16cabeb62ee0.png)

```
Logger: homeassistant.components.http.ban
Source: components/http/ban.py:80
Integration: HTTP (documentation, issues)
First occurred: 7:33:51 PM (1 occurrences)
Last logged: 7:33:51 PM

Login attempt or request with invalid authentication from localhost (127.0.0.1). Requested URL: '/api/websocket'. (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36)
```

```
Logger: homeassistant.components.http.ban
Source: components/http/ban.py:82
Integration: HTTP (documentation, issues)
First occurred: 7:31:33 PM (118 occurrences)
Last logged: 7:37:40 PM

Login attempt or request with invalid authentication from localhost (127.0.0.1). Requested URL: '/api/config'. (python-requests/2.28.2)
```

emhass log:
[5b918bf2_emhass_2023-03-07T18-36-07.809Z.log](https://github.com/davidusb-geek/emhass-add-on/files/10912905/5b918bf2_emhass_2023-03-07T18-36-07.809Z.log)

**Comment by davidusb-geek** [comment]
It works perfectly fine for me when I use duckdns and a token. I don't have nabu casa so I don't know about that.

**Comment by overas** [comment]
Thank you for the advice to use duckdns. Did not know about this service. I close the case because I migrated Home Assistant to only one Intel nuc.
