### ISSUE TITLE
ERROR - Either the names of the passed variables are not correct or days_to_retrieve is larger than the recorded history of your sensor (check your recorder settings)

### ISSUE THREAD

**Issue by vdiogo** [davidusb-geek/emhass-add-on#53]
Trying to run the ML Forecast model for my water sensor as per the steps here: https://community.home-assistant.io/t/machine-learning-models-for-time-series-forecast/546289 and getting an error after clicking on “ML forecast model fit”

This is my config:
```
hass_url: empty
long_lived_token: empty
costfun: cost
logging_level: DEBUG
optimization_time_step: 30
historic_days_to_retrieve: 7
method_ts_round: nearest
set_total_pv_sell: false
lp_solver: COIN_CMD
lp_solver_path: /usr/bin/cbc
set_nocharge_from_grid: false
set_nodischarge_to_grid: false
set_battery_dynamic: false
battery_dynamic_max: 0.9
battery_dynamic_min: -0.9
load_forecast_method: naive
sensor_power_photovoltaics: sensor.solax_pv_energy
sensor_power_load_no_var_loads: sensor.agua_streamlabs
number_of_deferrable_loads: 2
list_nominal_power_of_deferrable_loads:
  - nominal_power_of_deferrable_loads: 3000
  - nominal_power_of_deferrable_loads: 750
list_operating_hours_of_each_deferrable_load:
  - operating_hours_of_each_deferrable_load: 5
  - operating_hours_of_each_deferrable_load: 8
list_peak_hours_periods_start_hours:
  - peak_hours_periods_start_hours: "05:54"
  - peak_hours_periods_start_hours: "07:00"
list_peak_hours_periods_end_hours:
  - peak_hours_periods_end_hours: "09:24"
  - peak_hours_periods_end_hours: "09:55"
list_treat_deferrable_load_as_semi_cont:
  - treat_deferrable_load_as_semi_cont: true
  - treat_deferrable_load_as_semi_cont: true
load_peak_hours_cost: 0.1907
load_offpeak_hours_cost: 0.1419
photovoltaic_production_sell_price: 0.065
maximum_power_from_grid: 9000
list_pv_module_model:
  - pv_module_model: CSUN_Eurasia_Energy_Systems_Industry_and_Trade_CSUN295_60M
list_pv_inverter_model:
  - pv_inverter_model: Fronius_International_GmbH__Fronius_Primo_5_0_1_208_240__240V_
list_surface_tilt:
  - surface_tilt: 30
list_surface_azimuth:
  - surface_azimuth: 205
list_modules_per_string:
  - modules_per_string: 16
list_strings_per_inverter:
  - strings_per_inverter: 1
set_use_battery: false
battery_discharge_power_max: 1000
battery_charge_power_max: 1000
battery_discharge_efficiency: 0.95
battery_charge_efficiency: 0.95
battery_nominal_energy_capacity: 5000
battery_minimum_state_of_charge: 0.3
battery_maximum_state_of_charge: 0.9
battery_target_state_of_charge: 0.6

```

I get the following in EMHASS log:

```
2023-10-18 15:27:44,328 - web_server - ERROR - Either the names of the passed variables are not correct or days_to_retrieve is larger than the recorded history of your sensor (check your recorder settings)
2023-10-18 15:27:44,331 - web_server - ERROR - Exception on /action/forecast-model-fit [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/local/lib/python3.9/dist-packages/emhass/web_server.py", line 179, in action_call
    input_data_dict = set_input_data_dict(config_path, str(data_path), costfun,
  File "/usr/local/lib/python3.9/dist-packages/emhass/command_line.py", line 146, in set_input_data_dict
    rh.get_data(days_list, var_list)
  File "/usr/local/lib/python3.9/dist-packages/emhass/retrieve_hass.py", line 147, in get_data
    self.df_final = pd.concat([self.df_final, df_day], axis=0)
UnboundLocalError: local variable 'df_day' referenced before assignment
```

I have data recorded for the last 7 days:
<img width="546" alt="image" src="https://github.com/davidusb-geek/emhass-add-on/assets/24878195/f047da64-f8d7-4fa4-b733-5259ec86d4cd">

Any idea what the issue could be?

**Comment by davidusb-geek** [comment]
Hi, yes, follow the documentation here: https://emhass.readthedocs.io/en/latest/mlforecaster.html
For this to properly work you need to define a correct curl using shell command, just as we do for dayahead or MPC optimization calls.
You need to define this parameter that has a default value of 30 days:
```
"days_to_retrieve": 30
```
So set it to 7 days if that is what you have

**Comment by vdiogo** [comment]
Fantastic! 
<img width="1018" alt="image" src="https://github.com/davidusb-geek/emhass-add-on/assets/24878195/930b5d88-2dcb-4b12-89c4-d0d0eb964c8d">

**Comment by bf8392** [comment]
I'm new to EMHASS and have exactly the same error on initial start with basic config...@vdiogo can you post your working configuration?

**Comment by vdiogo** [comment]
> I'm new to EMHASS and have exactly the same error on initial start with basic config...@vdiogo can you post your working configuration?

I ended up de installing it as it didn't fit my purpose
