### ISSUE TITLE
ModuleNotFoundError: No module named 'web_server'

### ISSUE THREAD

**Issue by purcell-lab** [davidusb-geek/emhass-add-on#8]
emhass-add-on 0.2.5

```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun emhass (no readiness notification)
s6-rc: info: service legacy-services successfully started
[2022-05-14 12:01:45,718] INFO in web_server: Launching the emhass webserver at: http://0.0.0.0:5000
[2022-05-14 12:01:45,718] INFO in web_server: Home Assistant data fetch will be performed using url: http://supervisor/core/api
[2022-05-14 12:01:45,718] INFO in web_server: The base path is: /usr/src
[2022-05-14 12:01:45,723] INFO in web_server: Using core emhass version: 0.3.2
[2022-05-14 12:01:58,339] INFO in web_server: EMHASS server online, serving index.html...
INFO:web_server:EMHASS server online, serving index.html...
[2022-05-14 12:01:58,344] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.9/dist-packages/emhass/web_server.py", line 91, in index
    file_loader = PackageLoader('web_server')
  File "/usr/local/lib/python3.9/dist-packages/jinja2/loaders.py", line 291, in __init__
    import_module(package_name)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'web_server'
ERROR:web_server:Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.9/dist-packages/emhass/web_server.py", line 91, in index
    file_loader = PackageLoader('web_server')
  File "/usr/local/lib/python3.9/dist-packages/jinja2/loaders.py", line 291, in __init__
    import_module(package_name)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'web_server'

**Comment by davidusb-geek** [comment]
This was solved with the latests versions
